FileVersion = 1
Dependencies = {corlib = "*", nvrhi = "*", "nvrhi.validation" = "*", "nvrhi.vulkan" = "*", SDL2 = "*", "nvrhi.deviceManager" = "*", "nvrhi.shaderCompiler.HLSL" = "*", "nvrhi.sampleFramework" = "*"}

[Project]
Name = "nvrhi.test"
StartupObject = "nvrhi.test.Program"
