FileVersion = 1
Projects = {nvrhi = {Path = "Engine/nvrhi"}, Bulkan = {Path = "Dependencies/Bulkan"}, "nvrhi.test" = {Path = "Samples/nvrhi.test"}, "nvrhi.d3d11" = {Path = "Engine/nvrhi.d3d11"}, "nvrhi.d3d12" = {Path = "Engine/nvrhi.d3d12"}, "nvrhi.vulkan" = {Path = "Engine/nvrhi.vulkan"}, "nvrhi.validation" = {Path = "Engine/nvrhi.validation"}, SDL2 = "*", "nvrhi.deviceManager" = {Path = "Engine/nvrhi.deviceManager"}}
WorkspaceFolders = {Engine = ["nvrhi", "nvrhi.d3d11", "nvrhi.d3d12", "nvrhi.vulkan", "nvrhi.validation", "nvrhi.deviceManager"], Dependencies = ["corlib", "Bulkan", "SDL2"], Samples = ["nvrhi.test"]}

[Workspace]
StartupProject = "nvrhi.test"
